title: TAALED
lang: en
description: This is the official documentation of TAALED.

url: "https://lcr-ads-lab.github.io"
baseurl: "/TAALED"

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  
