title: TAALED
lang: en
description: This is the official documentation of TAALED.

remote_theme: clearpathrobotics/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
