title: TAALED
lang: en
description: This is the official documentation of TAALED.

url: "https://lcr-ads-lab.github.io"
baseurl: "/TAALED"

remote_theme: carlosperate/jekyll-theme-rtd
plugins:
  - jekyll-remote-theme
  - jekyll-readme-index

readme_index:
  with_frontmatter: true
